'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml

Namespace HoopDream.Framework.Schema

    <System.Diagnostics.DebuggerStepThrough()>
    Public Class RankRow
        Inherits DataRow

        Private _RankTable As RankTable

        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            _RankTable = CType(Me.Table, RankTable)
        End Sub

        Public Property PlayerID() As Integer
            Get
                Return CType(Me(_RankTable.PlayerIDColumn), Integer)
            End Get
            Set
                Me(_RankTable.PlayerIDColumn) = Value
            End Set
        End Property

        Public Property Rank() As Integer
            Get
                Return CType(Me(_RankTable.RankColumn), Integer)
            End Get
            Set
                Me(_RankTable.RankColumn) = Value
            End Set
        End Property

        Public Property Name() As String
            Get
                Return CType(Me(_RankTable.NameColumn), String)
            End Get
            Set
                Me(_RankTable.NameColumn) = Value
            End Set
        End Property

        Public Property Team() As String
            Get
                Return CType(Me(_RankTable.TeamColumn), String)
            End Get
            Set
                Me(_RankTable.TeamColumn) = Value
            End Set
        End Property

        Public Property Points() As Decimal
            Get
                Return CType(Me(_RankTable.PointsColumn), Decimal)
            End Get
            Set
                Me(_RankTable.PointsColumn) = Value
            End Set
        End Property

        Public Property FieldGoals() As Decimal
            Get
                Return CType(Me(_RankTable.FieldGoalsColumn), String)
            End Get
            Set
                Me(_RankTable.FieldGoalsColumn) = Value
            End Set
        End Property

        Public Property FreeThrowPercentageRank() As Decimal
            Get
                Return CType(Me(_RankTable.FreeThrowsColumn), Decimal)
            End Get
            Set
                Me(_RankTable.FreeThrowsColumn) = Value
            End Set
        End Property

        Public Property ThreePointRank() As Decimal
            Get
                Return CType(Me(_RankTable.ThreePointsColumn), Decimal)
            End Get
            Set
                Me(_RankTable.ThreePointsColumn) = Value
            End Set
        End Property

        Public Property ReboundRank() As Decimal
            Get
                Return CType(Me(_RankTable.ReboundsColumn), Decimal)
            End Get
            Set
                Me(_RankTable.ReboundsColumn) = Value
            End Set
        End Property

        Public Property AssistRank() As Decimal
            Get
                Return CType(Me(_RankTable.AssistsColumn), Decimal)
            End Get
            Set
                Me(_RankTable.AssistsColumn) = Value
            End Set
        End Property

        Public Property StealRank() As Decimal
            Get
                Return CType(Me(_RankTable.StealsColumn), Decimal)
            End Get
            Set
                Me(_RankTable.StealsColumn) = Value
            End Set
        End Property

        Public Property BlockRank() As Decimal
            Get
                Return CType(Me(_RankTable.BlocksColumn), Decimal)
            End Get
            Set
                Me(_RankTable.BlocksColumn) = Value
            End Set
        End Property

        Public Property TurnoverRank() As Decimal
            Get
                Return CType(Me(_RankTable.TurnoversColumn), Decimal)
            End Get
            Set
                Me(_RankTable.TurnoversColumn) = Value
            End Set
        End Property


        Public Function IsPlayerIDColumnNull() As Boolean
            Return Me.IsNull(_RankTable.RankColumn)
        End Function

        Public Function IsNameColumnNull() As Boolean
            Return Me.IsNull(_RankTable.NameColumn)
        End Function

        Public Sub SetPlayerIDColumnNull()
            Me(_RankTable.RankColumn) = System.Convert.DBNull
        End Sub

        Public Sub SetNameColumnNull()
            Me(_RankTable.NameColumn) = System.Convert.DBNull
        End Sub
    End Class
End Namespace
